server:
  port: 8081

spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: validate

jasypt:
  encryptor:
    password: ${jasypt_key}
    bean: jasyptEncryptor

jwt:
  secret: ${jwt_key}
  expiration_time: 600000              # 10분
  refresh_expiration_time: 1209600000  # 14일