server:
  port: 8081

spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: validate

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(EoaUR5bNyoV2eo8xT92t6yas9SMIc30welMDYyHrKRs=)
    password: ENC(OfvXV4Xs6CQP/cKno3BWvPDA6mI278DzBbbGMEkF2H4=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
    max_attempts: 5
    lock_minutes: 15
    expire_minutes: 5

jasypt:
  encryptor:
    password: ${jasypt_key}
    bean: jasyptEncryptor

jwt:
  secret: ${jwt_key}
  expiration_time: 600000              # 10분
  refresh_expiration_time: 1209600000  # 14일